-- Grainbuds real menu (from the previous website, prices in EUR).
-- Idempotent: re-running updates names/prices on existing slugs.
-- Run after schema.sql: SQL Editor -> New query -> paste -> Run.

insert into grainbuds_categories (name, name_de, slug, sort_order) values
  ('Specialty Matcha', 'Specialty Matcha', 'specialty-matcha', 1),
  ('Matcha Refresher', 'Matcha Refresher', 'matcha-refresher', 2),
  ('Hojicha', 'Hojicha', 'hojicha', 3),
  ('Smoothies', 'Smoothies', 'smoothies', 4),
  ('Fruit Tea', 'Früchtetee', 'fruit-tea', 5),
  ('Fruit Cloud', 'Fruit Cloud', 'fruit-cloud', 6),
  ('Tapioca Boba', 'Tapioka Boba', 'tapioca-boba', 7),
  ('Hosomaki (6 pieces)', 'Hosomaki (6 Stück)', 'hosomaki', 8),
  ('Uramaki (8 pieces)', 'Uramaki (8 Stück)', 'uramaki', 9),
  ('Special Rolls (8 pieces)', 'Spezial-Rollen (8 Stück)', 'special-rolls', 10),
  ('Nigiri (1 piece)', 'Nigiri (1 Stück)', 'nigiri', 11),
  ('Poké Bowls', 'Poké Bowls', 'poke-bowls', 12)
on conflict (slug) do update set name = excluded.name, name_de = excluded.name_de, sort_order = excluded.sort_order;

insert into grainbuds_products (category_id, name, name_de, slug, description, description_de, price_cents, image_url, is_featured, sort_order) values
  ((select id from grainbuds_categories where slug = 'specialty-matcha'), 'Matcha Latte Classic', 'Matcha Latte Classic', 'matcha-latte-classic', 'Matcha, milk', 'Matcha, Milch', 590, null, false, 1),
  ((select id from grainbuds_categories where slug = 'specialty-matcha'), 'Strawberry Matcha', 'Strawberry Matcha', 'strawberry-matcha', 'Matcha, strawberry purée, milk', 'Matcha, Erdbeerpüree, Milch', 620, null, false, 2),
  ((select id from grainbuds_categories where slug = 'specialty-matcha'), 'Mango Matcha', 'Mango Matcha', 'mango-matcha', 'Matcha, mango purée, milk', 'Matcha, Mangopüree, Milch', 620, null, false, 3),
  ((select id from grainbuds_categories where slug = 'specialty-matcha'), 'Pistachio Matcha', 'Pistazien-Matcha', 'pistachio-matcha', 'Matcha, pistachio cream, milk', 'Matcha, Pistaziencreme, Milch', 620, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/RbQeAvbFbXYmAj9mH.png', true, 4),
  ((select id from grainbuds_categories where slug = 'specialty-matcha'), 'White Choco Cream Matcha', 'White Choco Cream Matcha', 'white-choco-cream-matcha', 'Matcha, white chocolate cream, milk', 'Matcha, weiße Schokocreme, Milch', 620, null, false, 5),
  ((select id from grainbuds_categories where slug = 'specialty-matcha'), 'Ube Cream Top Matcha', 'Ube Cream Top Matcha', 'ube-cream-top-matcha', 'Matcha, ube, ube cream, milk', 'Matcha, Ube, Ube-Creme, Milch', 660, null, false, 6),
  ((select id from grainbuds_categories where slug = 'specialty-matcha'), 'Biscoff Banana Pudding Matcha', 'Biscoff Banana Pudding Matcha', 'biscoff-banana-pudding-matcha', 'Matcha, banana pudding, Biscoff, milk', 'Matcha, Bananenpudding, Biscoff, Milch', 660, null, false, 7),
  ((select id from grainbuds_categories where slug = 'specialty-matcha'), 'Cookies & Cream Pudding Matcha', 'Cookies & Cream Pudding Matcha', 'cookies-and-cream-pudding-matcha', 'Matcha, cookies, pudding, milk', 'Matcha, Kekse, Pudding, Milch', 700, null, false, 8),
  ((select id from grainbuds_categories where slug = 'specialty-matcha'), 'Black Sesame Matcha', 'Schwarzer-Sesam-Matcha', 'black-sesame-matcha', 'Matcha, roasted black sesame, milk', 'Matcha, gerösteter schwarzer Sesam, Milch', 660, null, true, 9),
  ((select id from grainbuds_categories where slug = 'matcha-refresher'), 'Yuzu Honey Soda Matcha', 'Yuzu Honey Soda Matcha', 'yuzu-honey-soda-matcha', 'Japanese citrus, honey soda, matcha', 'Japanische Zitrusfrucht, Honig-Soda, Matcha', 660, null, true, 10),
  ((select id from grainbuds_categories where slug = 'matcha-refresher'), 'Lychee Rose Soda Matcha', 'Lychee Rose Soda Matcha', 'lychee-rose-soda-matcha', 'Sweet lychee, rose soda, matcha', 'Süße Litschi, Rosen-Soda, Matcha', 660, null, false, 11),
  ((select id from grainbuds_categories where slug = 'matcha-refresher'), 'Coconut Water Usucha', 'Coconut Water Usucha', 'coconut-water-usucha', 'Coconut water, matcha', 'Kokoswasser, Matcha', 680, null, false, 12),
  ((select id from grainbuds_categories where slug = 'hojicha'), 'Hojicha Latte Classic', 'Hojicha Latte Classic', 'hojicha-latte-classic', 'Hojicha, milk', 'Hojicha, Milch', 590, null, false, 13),
  ((select id from grainbuds_categories where slug = 'hojicha'), 'Strawberry Hojicha', 'Strawberry Hojicha', 'strawberry-hojicha', 'Hojicha, strawberry purée, milk', 'Hojicha, Erdbeerpüree, Milch', 620, null, false, 14),
  ((select id from grainbuds_categories where slug = 'hojicha'), 'Maple Toffee Hojicha', 'Maple Toffee Hojicha', 'maple-toffee-hojicha', 'Hojicha, maple syrup, toffee, milk', 'Hojicha, Ahornsirup, Toffee, Milch', 620, null, false, 15),
  ((select id from grainbuds_categories where slug = 'hojicha'), 'Biscoff Banana Pudding Hojicha', 'Biscoff Banana Pudding Hojicha', 'biscoff-banana-pudding-hojicha', 'Hojicha, banana pudding, Biscoff, milk', 'Hojicha, Bananenpudding, Biscoff, Milch', 660, null, false, 16),
  ((select id from grainbuds_categories where slug = 'hojicha'), 'Black Sesame Hojicha', 'Schwarzer-Sesam-Hojicha', 'black-sesame-hojicha', 'Hojicha, roasted black sesame, milk', 'Hojicha, gerösteter schwarzer Sesam, Milch', 660, null, false, 17),
  ((select id from grainbuds_categories where slug = 'smoothies'), 'Berry Crush', 'Berry Crush', 'berry-crush', 'Strawberry, raspberry, goji, yogurt', 'Erdbeere, Himbeere, Goji, Joghurt', 650, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/CaAcePPceQWRMKEnJ.png', true, 18),
  ((select id from grainbuds_categories where slug = 'smoothies'), 'Golden Mood', 'Golden Mood', 'golden-mood', 'Mango, pineapple, dates, yogurt', 'Mango, Ananas, Datteln, Joghurt', 650, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/tXAj9EESxgJbGBeMe.png', false, 19),
  ((select id from grainbuds_categories where slug = 'smoothies'), 'Blue Earth', 'Blue Earth', 'blue-earth', 'Avocado, banana, yogurt, honey, spirulina', 'Avocado, Banane, Joghurt, Honig, Spirulina', 650, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/wCZd37cua4A2etDMP.png', false, 20),
  ((select id from grainbuds_categories where slug = 'smoothies'), 'Tropical Pink', 'Tropical Pink', 'tropical-pink', 'Dragonfruit, strawberry, banana, vanilla, yogurt', 'Drachenfrucht, Erdbeere, Banane, Vanille, Joghurt', 680, null, false, 21),
  ((select id from grainbuds_categories where slug = 'fruit-tea'), 'Grape Lime Tea', 'Trauben-Limetten-Tee', 'grape-lime-tea', 'Freshly crushed grapes and lime, jasmine tea', 'Frisch gestoßene Trauben und Limette, Jasmintee', 680, null, false, 22),
  ((select id from grainbuds_categories where slug = 'fruit-tea'), 'Mango Passionfruit Tea', 'Mango-Maracuja-Tee', 'mango-passionfruit-tea', 'Freshly crushed mango and passionfruit, jasmine tea', 'Frisch gestoßene Mango und Maracuja, Jasmintee', 680, null, false, 23),
  ((select id from grainbuds_categories where slug = 'fruit-tea'), 'Mango Coco', 'Mango Coco', 'mango-coco', 'Mango, grapefruit, jasmine tea, coconut milk, mango slush', 'Mango, Grapefruit, Jasmintee, Kokosmilch, Mango-Slush', 700, null, false, 24),
  ((select id from grainbuds_categories where slug = 'fruit-cloud'), 'Lychee Cloud', 'Lychee Cloud', 'lychee-cloud', 'Lychee under a soft cream cloud', 'Litschi unter einer zarten Cremewolke', 620, null, false, 25),
  ((select id from grainbuds_categories where slug = 'fruit-cloud'), 'Mango Cloud', 'Mango Cloud', 'mango-cloud', 'Mango under a soft cream cloud', 'Mango unter einer zarten Cremewolke', 620, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/tRFWMX83Q9tJHTAxh.png', true, 26),
  ((select id from grainbuds_categories where slug = 'fruit-cloud'), 'Strawberry Cloud', 'Strawberry Cloud', 'strawberry-cloud', 'Strawberry under a soft cream cloud', 'Erdbeere unter einer zarten Cremewolke', 620, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/2dWxNtvg76FTAifGb.png', false, 27),
  ((select id from grainbuds_categories where slug = 'fruit-cloud'), 'Grape Cloud', 'Grape Cloud', 'grape-cloud', 'Grape under a soft cream cloud', 'Traube unter einer zarten Cremewolke', 620, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/Nb4wNxbR5NfGK8etu.png', false, 28),
  ((select id from grainbuds_categories where slug = 'fruit-cloud'), 'Passionfruit Peach Cloud', 'Maracuja-Pfirsich Cloud', 'passionfruit-peach-cloud', 'Passionfruit and peach under a soft cream cloud', 'Maracuja und Pfirsich unter einer zarten Cremewolke', 620, null, false, 29),
  ((select id from grainbuds_categories where slug = 'tapioca-boba'), 'Tapioca Brown Sugar Milk Tea', 'Tapioka Brown Sugar Milktea', 'tapioca-brown-sugar-milk-tea', 'Milk tea with brown sugar tapioca pearls', 'Milchtee mit Brown-Sugar-Tapiokaperlen', 590, null, false, 30),
  ((select id from grainbuds_categories where slug = 'tapioca-boba'), 'Tapioca Matcha', 'Tapioka Matcha', 'tapioca-matcha', 'Matcha latte with tapioca pearls', 'Matcha Latte mit Tapiokaperlen', 680, null, false, 31),
  ((select id from grainbuds_categories where slug = 'tapioca-boba'), 'Tapioca Ube with Cream', 'Tapioka Ube mit Creme', 'tapioca-ube-with-cream', 'Ube milk with tapioca pearls and cream top', 'Ube-Milch mit Tapiokaperlen und Cremehaube', 660, null, false, 32),
  ((select id from grainbuds_categories where slug = 'hosomaki'), 'No. 101 Kappa', 'Nr. 101 Kappa', 'no-101-kappa', 'Cucumber', 'Gurke', 390, null, false, 33),
  ((select id from grainbuds_categories where slug = 'hosomaki'), 'No. 102 Avocado', 'Nr. 102 Avocado', 'no-102-avocado', 'Avocado', 'Avocado', 420, null, false, 34),
  ((select id from grainbuds_categories where slug = 'hosomaki'), 'No. 103 Mango', 'Nr. 103 Mango', 'no-103-mango', 'Mango', 'Mango', 420, null, false, 35),
  ((select id from grainbuds_categories where slug = 'hosomaki'), 'No. 104 Asupa', 'Nr. 104 Asupa', 'no-104-asupa', 'Asparagus', 'Spargel', 420, null, false, 36),
  ((select id from grainbuds_categories where slug = 'hosomaki'), 'No. 105 Sake', 'Nr. 105 Sake', 'no-105-sake', 'Salmon', 'Lachs', 480, null, false, 37),
  ((select id from grainbuds_categories where slug = 'uramaki'), 'No. 120 Alasuka', 'Nr. 120 Alasuka', 'no-120-alasuka', '', '', 790, null, false, 38),
  ((select id from grainbuds_categories where slug = 'uramaki'), 'No. 121 Chili Roll', 'Nr. 121 Chili Roll', 'no-121-chili-roll', '', '', 790, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/Drp785pNzhomKaP3p.png', true, 39),
  ((select id from grainbuds_categories where slug = 'uramaki'), 'No. 122 California', 'Nr. 122 California', 'no-122-california', '', '', 790, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/9koNHkS7zGrxRxPRy.png', false, 40),
  ((select id from grainbuds_categories where slug = 'uramaki'), 'No. 123 Salmon-Avo', 'Nr. 123 Lachs-Avo', 'no-123-salmon-avo', 'Salmon, avocado', 'Lachs, Avocado', 790, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/37RC7ySvWp99FZ9wh.png', false, 41),
  ((select id from grainbuds_categories where slug = 'uramaki'), 'No. 124 Philadelphia', 'Nr. 124 Philadelphia', 'no-124-philadelphia', '', '', 790, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/4fbiuuNsNystdEr3g.png', false, 42),
  ((select id from grainbuds_categories where slug = 'uramaki'), 'No. 125 Narumi', 'Nr. 125 Narumi', 'no-125-narumi', '', '', 790, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/zimjAFwXCZKLqogNi.png', false, 43),
  ((select id from grainbuds_categories where slug = 'uramaki'), 'No. 126 Simizu', 'Nr. 126 Simizu', 'no-126-simizu', '', '', 650, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/ttFF6EqZ9eC6fZMGZ.png', false, 44),
  ((select id from grainbuds_categories where slug = 'uramaki'), 'No. 128 Sake Kawa', 'Nr. 128 Sake Kawa', 'no-128-sake-kawa', '', '', 950, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/ESt8gn26tDQ3rKqsn.png', false, 45),
  ((select id from grainbuds_categories where slug = 'uramaki'), 'No. 129 Inari Roll', 'Nr. 129 Inari Roll', 'no-129-inari-roll', '', '', 950, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/eYQ2xobjtqxnsXXgt.png', false, 46),
  ((select id from grainbuds_categories where slug = 'special-rolls'), 'Flambé Roll', 'Flambé Roll', 'flambe-roll', '', '', 1350, null, false, 47),
  ((select id from grainbuds_categories where slug = 'special-rolls'), 'No. 131 Yoshi', 'Nr. 131 Yoshi', 'no-131-yoshi', '', '', 1290, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/cTw2GW6DQQybXfnEg.png', true, 48),
  ((select id from grainbuds_categories where slug = 'special-rolls'), 'No. 133 Sate Roll', 'Nr. 133 Sate-Roll', 'no-133-sate-roll', '', '', 1090, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/YwXbiaHyFWbZjavuH.png', false, 49),
  ((select id from grainbuds_categories where slug = 'special-rolls'), 'No. 134 Rainbow Roll (spicy)', 'Nr. 134 Rainbow Roll (scharf)', 'no-134-rainbow-roll-spicy', '', '', 1290, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/ocb96jZbA8p34ahxQ.png', false, 50),
  ((select id from grainbuds_categories where slug = 'nigiri'), 'No. 141 Sake', 'Nr. 141 Sake', 'no-141-sake', 'Salmon', 'Lachs', 290, null, false, 51),
  ((select id from grainbuds_categories where slug = 'nigiri'), 'No. 142 Sake Flambé', 'Nr. 142 Sake flambiert', 'no-142-sake-flambe', 'Flamed salmon', 'Flambierter Lachs', 350, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/Yqjs54jxfwPDgctsm.png', false, 52),
  ((select id from grainbuds_categories where slug = 'nigiri'), 'No. 143 Spicy Sake', 'Nr. 143 Spicy Sake', 'no-143-spicy-sake', 'Spicy salmon', 'Pikanter Lachs', 350, 'https://ams3.digitaloceanspaces.com/tmi-images/grainbuds__asian_cafe_143/menu/dishes/b8tpNpeQ2756tT9Ph.png', false, 53),
  ((select id from grainbuds_categories where slug = 'nigiri'), 'No. 146 Edamame (vegan)', 'Nr. 146 Edamame (vegan)', 'no-146-edamame-vegan', '', '', 590, null, false, 54),
  ((select id from grainbuds_categories where slug = 'poke-bowls'), 'No. 150 Chicken Teriyaki Poké Bowl', 'Nr. 150 Hähnchen-Teriyaki Poké Bowl', 'no-150-chicken-teriyaki-poke-bowl', '', '', 1290, null, false, 55),
  ((select id from grainbuds_categories where slug = 'poke-bowls'), 'No. 151 Salmon Poké Bowl', 'Nr. 151 Lachs Poké Bowl', 'no-151-salmon-poke-bowl', '', '', 1350, null, true, 56),
  ((select id from grainbuds_categories where slug = 'poke-bowls'), 'No. 152 Tofu Poké Bowl', 'Nr. 152 Tofu Poké Bowl', 'no-152-tofu-poke-bowl', '', '', 1190, null, false, 57)
on conflict (slug) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  name_de = excluded.name_de,
  description = excluded.description,
  description_de = excluded.description_de,
  price_cents = excluded.price_cents,
  image_url = coalesce(grainbuds_products.image_url, excluded.image_url),
  is_featured = excluded.is_featured,
  sort_order = excluded.sort_order;
